---
- hosts: localhost
  connection: local
  tasks:
    - name: Cleanup directories & files to start from scratch
      file: path={{ item }} state=absent
      with_items: 
        - ./inventory
        - ./group_vars

    - name: Create inventory file
      file: path=./inventory state=touch

    - name: Create directories group_vars & host_vars
      file: path={{ item }} state=directory
      with_items: 
        - ./group_vars
